# Generated by Django 5.2.1 on 2026-03-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owner_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='phone',
            field=models.CharField(default='91xxxxxxxx', max_length=15),
        ),
    ]
